# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
# 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred divisors?

# Python program to print prime factors

import math


# A function to print all prime factors of
# a given number n

import math


def num_factors(n):
    print(n)
    ret = 2
    for j in range(2, int(math.sqrt(n))):
        if n % j == 0:
            ret += 2
    print(" ", ret)
    return ret


f_num = 0
i = 1
tri = 0
while f_num <= 500:
    tri += i
    i += 1
    f_num = num_factors(tri)

print("-", tri)
